// 20230506144056
// http://localhost:3001/dogs/api

[
    {
      "id": 1,
      "name": "Affenpinscher",
      "alturaMax": "29",
      "alturaMin": "23",
      "pesoMax": "6",
      "pesoMin": "3",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
      "image": "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
      "type": "api"
    },
    {
      "id": 2,
      "name": "Afghan Hound",
      "alturaMax": "69",
      "alturaMin": "64",
      "pesoMax": "27",
      "pesoMin": "23",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Aloof, Clownish, Dignified, Independent, Happy",
      "image": "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
      "type": "api"
    },
    {
      "id": 3,
      "name": "African Hunting Dog",
      "alturaMin": "76",
      "pesoMax": "30",
      "pesoMin": "20",
      "vidaMin": "11 years",
      "temperaments": "Wild, Hardworking, Dutiful",
      "image": "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
      "type": "api"
    },
    {
      "id": 4,
      "name": "Airedale Terrier",
      "alturaMax": "58",
      "alturaMin": "53",
      "pesoMax": "29",
      "pesoMin": "18",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
      "image": "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
      "type": "api"
    },
    {
      "id": 5,
      "name": "Akbash Dog",
      "alturaMax": "86",
      "alturaMin": "71",
      "pesoMax": "54",
      "pesoMin": "41",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Loyal, Independent, Intelligent, Brave",
      "image": "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
      "type": "api"
    },
    {
      "id": 6,
      "name": "Akita",
      "alturaMax": "71",
      "alturaMin": "61",
      "pesoMax": "52",
      "pesoMin": "29",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
      "image": "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
      "type": "api"
    },
    {
      "id": 7,
      "name": "Alapaha Blue Blood Bulldog",
      "alturaMax": "61",
      "alturaMin": "46",
      "pesoMax": "41",
      "pesoMin": "25",
      "vidaMax": "13 years",
      "vidaMin": "12",
      "temperaments": "Loving, Protective, Trainable, Dutiful, Responsible",
      "image": "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
      "type": "api"
    },
    {
      "id": 8,
      "name": "Alaskan Husky",
      "alturaMax": "66",
      "alturaMin": "58",
      "pesoMax": "23",
      "pesoMin": "17",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Friendly, Energetic, Loyal, Gentle, Confident",
      "image": "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
      "type": "api"
    },
    {
      "id": 9,
      "name": "Alaskan Malamute",
      "alturaMax": "64",
      "alturaMin": "58",
      "pesoMax": "45",
      "pesoMin": "29",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
      "image": "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
      "type": "api"
    },
    {
      "id": 10,
      "name": "American Bulldog",
      "alturaMax": "69",
      "alturaMin": "56",
      "pesoMax": "54",
      "pesoMin": "27",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
      "image": "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
      "type": "api"
    },
    {
      "id": 11,
      "name": "American Bully",
      "alturaMax": "43",
      "alturaMin": "36",
      "pesoMax": "68",
      "pesoMin": "14",
      "vidaMin": "8 – 15 years",
      "temperaments": "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
      "image": "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
      "type": "api"
    },
    {
      "id": 12,
      "name": "American Eskimo Dog",
      "alturaMax": "48",
      "alturaMin": "38",
      "pesoMax": "18",
      "pesoMin": "9",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Alert, Reserved, Intelligent, Protective",
      "image": "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
      "type": "api"
    },
    {
      "id": 13,
      "name": "American Eskimo Dog (Miniature)",
      "alturaMax": "30",
      "alturaMin": "23",
      "pesoMax": "5",
      "pesoMin": "3",
      "vidaMin": "13 – 15 years",
      "temperaments": "Friendly, Alert, Reserved, Intelligent, Protective",
      "image": "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
      "type": "api"
    },
    {
      "id": 14,
      "name": "American Foxhound",
      "alturaMax": "71",
      "alturaMin": "53",
      "pesoMax": "34",
      "pesoMin": "29",
      "vidaMax": "15 years",
      "vidaMin": "8",
      "temperaments": "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
      "image": "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
      "type": "api"
    },
    {
      "id": 15,
      "name": "American Pit Bull Terrier",
      "alturaMax": "53",
      "alturaMin": "43",
      "pesoMax": "27",
      "pesoMin": "14",
      "vidaMax": "15 years",
      "vidaMin": "10",
      "temperaments": "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
      "image": "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
      "type": "api"
    },
    {
      "id": 16,
      "name": "American Staffordshire Terrier",
      "alturaMax": "48",
      "alturaMin": "43",
      "pesoMax": "27",
      "pesoMin": "23",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
      "image": "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
      "type": "api"
    },
    {
      "id": 17,
      "name": "American Water Spaniel",
      "alturaMax": "46",
      "alturaMin": "38",
      "pesoMax": "20",
      "pesoMin": "11",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
      "image": "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
      "type": "api"
    },
    {
      "id": 18,
      "name": "Anatolian Shepherd Dog",
      "alturaMax": "74",
      "alturaMin": "69",
      "pesoMax": "68",
      "pesoMin": "36",
      "vidaMax": "13 years",
      "vidaMin": "11",
      "temperaments": "Steady, Bold, Independent, Confident, Intelligent, Proud",
      "image": "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
      "type": "api"
    },
    {
      "id": 19,
      "name": "Appenzeller Sennenhund",
      "alturaMax": "56",
      "alturaMin": "51",
      "pesoMax": "25",
      "pesoMin": "22",
      "vidaMin": "12 – 14 years",
      "temperaments": "Reliable, Fearless, Energetic, Lively, Self-assured",
      "image": "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
      "type": "api"
    },
    {
      "id": 21,
      "name": "Australian Cattle Dog",
      "alturaMax": "51",
      "alturaMin": "43",
      "pesoMax": "28",
      "pesoMin": "20",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
      "image": "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
      "type": "api"
    },
    {
      "id": 22,
      "name": "Australian Kelpie",
      "alturaMax": "51",
      "alturaMin": "43",
      "pesoMax": "21",
      "pesoMin": "14",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
      "image": "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
      "type": "api"
    },
    {
      "id": 23,
      "name": "Australian Shepherd",
      "alturaMax": "58",
      "alturaMin": "46",
      "pesoMax": "29",
      "pesoMin": "16",
      "vidaMax": "16 years",
      "vidaMin": "12",
      "temperaments": "Good-natured, Affectionate, Intelligent, Active, Protective",
      "image": "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
      "type": "api"
    },
    {
      "id": 24,
      "name": "Australian Terrier",
      "alturaMax": "28",
      "alturaMin": "25",
      "pesoMax": "7",
      "pesoMin": "6",
      "vidaMin": "15 years",
      "temperaments": "Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous",
      "image": "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
      "type": "api"
    },
    {
      "id": 25,
      "name": "Azawakh",
      "alturaMax": "74",
      "alturaMin": "58",
      "pesoMax": "25",
      "pesoMin": "15",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Aloof, Affectionate, Attentive, Rugged, Fierce, Refined",
      "image": "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
      "type": "api"
    },
    {
      "id": 26,
      "name": "Barbet",
      "alturaMax": "66",
      "alturaMin": "51",
      "pesoMax": "29",
      "pesoMin": "18",
      "vidaMin": "13 – 15 years",
      "temperaments": "Obedient, Companionable, Intelligent, Joyful",
      "image": "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
      "type": "api"
    },
    {
      "id": 28,
      "name": "Basenji",
      "alturaMax": "43",
      "alturaMin": "41",
      "pesoMax": "11",
      "pesoMin": "10",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Energetic, Alert, Curious, Playful, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
      "type": "api"
    },
    {
      "id": 29,
      "name": "Basset Bleu de Gascogne",
      "alturaMax": "38",
      "alturaMin": "33",
      "pesoMax": "18",
      "pesoMin": "16",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Lively, Agile, Curious, Happy, Active",
      "image": "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
      "type": "api"
    },
    {
      "id": 30,
      "name": "Basset Hound",
      "alturaMin": "36",
      "pesoMax": "29",
      "pesoMin": "23",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle",
      "image": "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
      "type": "api"
    },
    {
      "id": 31,
      "name": "Beagle",
      "alturaMax": "38",
      "alturaMin": "33",
      "pesoMax": "16",
      "pesoMin": "9",
      "vidaMax": "16 years",
      "vidaMin": "13",
      "temperaments": "Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
      "type": "api"
    },
    {
      "id": 32,
      "name": "Bearded Collie",
      "alturaMax": "56",
      "alturaMin": "51",
      "pesoMax": "25",
      "pesoMin": "20",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Self-confidence, Hardy, Lively, Alert, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
      "type": "api"
    },
    {
      "id": 33,
      "name": "Beauceron",
      "alturaMax": "70",
      "alturaMin": "61",
      "pesoMax": "50",
      "pesoMin": "36",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Fearless, Friendly, Intelligent, Protective, Calm",
      "image": "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
      "type": "api"
    },
    {
      "id": 34,
      "name": "Bedlington Terrier",
      "alturaMax": "41",
      "alturaMin": "38",
      "pesoMax": "10",
      "pesoMin": "8",
      "vidaMax": "16 years",
      "vidaMin": "14",
      "temperaments": "Affectionate, Spirited, Intelligent, Good-tempered",
      "image": "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
      "type": "api"
    },
    {
      "id": 36,
      "name": "Belgian Malinois",
      "alturaMax": "66",
      "alturaMin": "56",
      "pesoMax": "36",
      "pesoMin": "18",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective",
      "image": "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
      "type": "api"
    },
    {
      "id": 38,
      "name": "Belgian Tervuren",
      "alturaMax": "66",
      "alturaMin": "56",
      "pesoMax": "29",
      "pesoMin": "18",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Energetic, Alert, Loyal, Intelligent, Attentive, Protective",
      "image": "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
      "type": "api"
    },
    {
      "id": 41,
      "name": "Bernese Mountain Dog",
      "alturaMax": "70",
      "alturaMin": "58",
      "pesoMax": "54",
      "pesoMin": "29",
      "vidaMax": "10 years",
      "vidaMin": "7",
      "temperaments": "Affectionate, Loyal, Intelligent, Faithful",
      "image": "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
      "type": "api"
    },
    {
      "id": 42,
      "name": "Bichon Frise",
      "alturaMax": "29",
      "alturaMin": "24",
      "pesoMax": "8",
      "pesoMin": "5",
      "vidaMin": "15 years",
      "temperaments": "Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive",
      "image": "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
      "type": "api"
    },
    {
      "id": 43,
      "name": "Black and Tan Coonhound",
      "alturaMax": "69",
      "alturaMin": "58",
      "pesoMax": "45",
      "pesoMin": "29",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable",
      "image": "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
      "type": "api"
    },
    {
      "id": 45,
      "name": "Bloodhound",
      "alturaMax": "69",
      "alturaMin": "58",
      "pesoMax": "50",
      "pesoMin": "36",
      "vidaMax": "10 years",
      "vidaMin": "8",
      "temperaments": "Stubborn, Affectionate, Gentle, Even Tempered",
      "image": "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
      "type": "api"
    },
    {
      "id": 47,
      "name": "Bluetick Coonhound",
      "alturaMax": "69",
      "alturaMin": "53",
      "pesoMax": "36",
      "pesoMin": "20",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
      "type": "api"
    },
    {
      "id": 48,
      "name": "Boerboel",
      "alturaMax": "69",
      "alturaMin": "56",
      "pesoMax": "91",
      "pesoMin": "50",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Obedient, Confident, Intelligent, Dominant, Territorial",
      "image": "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
      "type": "api"
    },
    {
      "id": 50,
      "name": "Border Collie",
      "alturaMax": "56",
      "alturaMin": "46",
      "pesoMax": "20",
      "pesoMin": "14",
      "vidaMax": "16 years",
      "vidaMin": "12",
      "temperaments": "Tenacious, Keen, Energetic, Responsive, Alert, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
      "type": "api"
    },
    {
      "id": 51,
      "name": "Border Terrier",
      "alturaMax": "41",
      "alturaMin": "28",
      "pesoMax": "7",
      "pesoMin": "5",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered",
      "image": "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
      "type": "api"
    },
    {
      "id": 53,
      "name": "Boston Terrier",
      "alturaMax": "43",
      "alturaMin": "41",
      "pesoMax": "11",
      "pesoMin": "5",
      "vidaMax": "13 years",
      "vidaMin": "11",
      "temperaments": "Friendly, Lively, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
      "type": "api"
    },
    {
      "id": 54,
      "name": "Bouvier des Flandres",
      "alturaMax": "70",
      "alturaMin": "60",
      "pesoMax": "50",
      "pesoMin": "32",
      "vidaMax": "15 years",
      "vidaMin": "10",
      "temperaments": "Protective, Loyal, Gentle, Intelligent, Familial, Rational",
      "image": "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
      "type": "api"
    },
    {
      "id": 55,
      "name": "Boxer",
      "alturaMax": "64",
      "alturaMin": "55",
      "pesoMax": "32",
      "pesoMin": "23",
      "vidaMax": "10 years",
      "vidaMin": "8",
      "temperaments": "Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm",
      "image": "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
      "type": "api"
    },
    {
      "id": 56,
      "name": "Boykin Spaniel",
      "alturaMax": "46",
      "alturaMin": "36",
      "pesoMax": "18",
      "pesoMin": "11",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Friendly, Energetic, Companionable, Intelligent, Eager, Trainable",
      "image": "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
      "type": "api"
    },
    {
      "id": 57,
      "name": "Bracco Italiano",
      "alturaMax": "67",
      "alturaMin": "55",
      "pesoMax": "40",
      "pesoMin": "25",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable",
      "image": "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
      "type": "api"
    },
    {
      "id": 58,
      "name": "Briard",
      "alturaMax": "69",
      "alturaMin": "56",
      "pesoMax": "41",
      "pesoMin": "32",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Fearless, Loyal, Obedient, Intelligent, Faithful, Protective",
      "image": "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
      "type": "api"
    },
    {
      "id": 59,
      "name": "Brittany",
      "alturaMax": "52",
      "alturaMin": "44",
      "pesoMax": "20",
      "pesoMin": "14",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Agile, Adaptable, Quick, Intelligent, Attentive, Happy",
      "image": "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
      "type": "api"
    },
    {
      "id": 61,
      "name": "Bull Terrier",
      "alturaMax": "56",
      "alturaMin": "53",
      "pesoMax": "32",
      "pesoMin": "23",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Trainable, Protective, Sweet-Tempered, Keen, Active",
      "image": "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
      "type": "api"
    },
    {
      "id": 62,
      "name": "Bull Terrier (Miniature)",
      "alturaMax": "36",
      "alturaMin": "25",
      "pesoMax": "15",
      "pesoMin": "11",
      "vidaMin": "11 – 14 years",
      "temperaments": "Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial",
      "image": "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
      "type": "api"
    },
    {
      "id": 64,
      "name": "Bullmastiff",
      "alturaMax": "69",
      "alturaMin": "61",
      "pesoMax": "59",
      "pesoMin": "45",
      "vidaMax": "12 years",
      "vidaMin": "8",
      "temperaments": "Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous",
      "image": "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
      "type": "api"
    },
    {
      "id": 65,
      "name": "Cairn Terrier",
      "alturaMax": "25",
      "alturaMin": "23",
      "pesoMax": "6",
      "pesoMin": "6",
      "vidaMax": "15 years",
      "vidaMin": "14",
      "temperaments": "Hardy, Fearless, Assertive, Gay, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
      "type": "api"
    },
    {
      "id": 67,
      "name": "Cane Corso",
      "alturaMax": "70",
      "alturaMin": "60",
      "pesoMax": "54",
      "pesoMin": "40",
      "vidaMax": "11 years",
      "vidaMin": "10",
      "temperaments": "Trainable, Reserved, Stable, Quiet, Even Tempered, Calm",
      "image": "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
      "type": "api"
    },
    {
      "id": 68,
      "name": "Cardigan Welsh Corgi",
      "alturaMax": "32",
      "alturaMin": "27",
      "pesoMax": "17",
      "pesoMin": "11",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Devoted, Alert, Companionable, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
      "type": "api"
    },
    {
      "id": 69,
      "name": "Catahoula Leopard Dog",
      "alturaMax": "66",
      "alturaMin": "51",
      "pesoMax": "43",
      "pesoMin": "23",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving",
      "image": "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
      "type": "api"
    },
    {
      "id": 70,
      "name": "Caucasian Shepherd (Ovcharka)",
      "alturaMax": "85",
      "alturaMin": "61",
      "pesoMax": "45",
      "pesoMin": "36",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Alert, Quick, Dominant, Powerful, Calm, Strong",
      "image": "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
      "type": "api"
    },
    {
      "id": 71,
      "name": "Cavalier King Charles Spaniel",
      "alturaMax": "33",
      "alturaMin": "30",
      "pesoMax": "8",
      "pesoMin": "6",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Fearless, Affectionate, Sociable, Patient, Playful, Adaptable",
      "image": "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
      "type": "api"
    },
    {
      "id": 76,
      "name": "Chesapeake Bay Retriever",
      "alturaMax": "66",
      "alturaMin": "53",
      "pesoMax": "36",
      "pesoMin": "25",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Intelligent, Quiet, Dominant, Happy, Protective",
      "image": "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
      "type": "api"
    },
    {
      "id": 78,
      "name": "Chinese Crested",
      "alturaMax": "33",
      "alturaMin": "28",
      "pesoMax": "6",
      "pesoMin": "5",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy",
      "image": "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
      "type": "api"
    },
    {
      "id": 79,
      "name": "Chinese Shar-Pei",
      "alturaMax": "51",
      "alturaMin": "46",
      "pesoMax": "27",
      "pesoMin": "20",
      "vidaMin": "10 years",
      "temperaments": "Suspicious, Affectionate, Devoted, Reserved, Independent, Loving",
      "image": "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
      "type": "api"
    },
    {
      "id": 80,
      "name": "Chinook",
      "alturaMax": "66",
      "alturaMin": "56",
      "pesoMax": "41",
      "pesoMin": "23",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Alert, Dignified, Intelligent, Calm",
      "image": "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
      "type": "api"
    },
    {
      "id": 81,
      "name": "Chow Chow",
      "alturaMax": "51",
      "alturaMin": "43",
      "pesoMax": "32",
      "pesoMin": "18",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Aloof, Loyal, Independent, Quiet",
      "image": "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
      "type": "api"
    },
    {
      "id": 84,
      "name": "Clumber Spaniel",
      "alturaMax": "51",
      "alturaMin": "43",
      "pesoMax": "39",
      "pesoMin": "25",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted",
      "image": "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
      "type": "api"
    },
    {
      "id": 86,
      "name": "Cocker Spaniel",
      "alturaMax": "38",
      "alturaMin": "36",
      "pesoMax": "14",
      "pesoMin": "9",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Trainable, Friendly, Affectionate, Playful, Quiet, Faithful",
      "image": "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
      "type": "api"
    },
    {
      "id": 87,
      "name": "Cocker Spaniel (American)",
      "alturaMax": "38",
      "alturaMin": "36",
      "pesoMax": "14",
      "pesoMin": "9",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry",
      "image": "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
      "type": "api"
    },
    {
      "id": 89,
      "name": "Coton de Tulear",
      "alturaMax": "28",
      "alturaMin": "23",
      "pesoMax": "7",
      "pesoMin": "4",
      "vidaMax": "16 years",
      "vidaMin": "13",
      "temperaments": "Affectionate, Lively, Playful, Intelligent, Trainable, Vocal",
      "image": "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
      "type": "api"
    },
    {
      "id": 92,
      "name": "Dalmatian",
      "alturaMax": "58",
      "alturaMin": "48",
      "pesoMax": "25",
      "pesoMin": "23",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
      "type": "api"
    },
    {
      "id": 94,
      "name": "Doberman Pinscher",
      "alturaMax": "71",
      "alturaMin": "61",
      "pesoMax": "40",
      "pesoMin": "30",
      "vidaMin": "10 years",
      "temperaments": "Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
      "type": "api"
    },
    {
      "id": 95,
      "name": "Dogo Argentino",
      "alturaMax": "69",
      "alturaMin": "60",
      "pesoMax": "45",
      "pesoMin": "36",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective",
      "image": "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
      "type": "api"
    },
    {
      "id": 98,
      "name": "Dutch Shepherd",
      "alturaMax": "62",
      "alturaMin": "56",
      "pesoMax": "32",
      "pesoMin": "23",
      "vidaMin": "15 years",
      "temperaments": "Reliable, Affectionate, Alert, Loyal, Obedient, Trainable",
      "image": "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
      "type": "api"
    },
    {
      "id": 101,
      "name": "English Setter",
      "alturaMax": "64",
      "alturaMin": "61",
      "pesoMax": "36",
      "pesoMin": "20",
      "vidaMin": "12 years",
      "temperaments": "Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented",
      "image": "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
      "type": "api"
    },
    {
      "id": 102,
      "name": "English Shepherd",
      "alturaMax": "58",
      "alturaMin": "46",
      "pesoMax": "30",
      "pesoMin": "20",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Kind, Energetic, Independent, Adaptable, Intelligent, Bossy",
      "image": "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
      "type": "api"
    },
    {
      "id": 103,
      "name": "English Springer Spaniel",
      "alturaMax": "51",
      "alturaMin": "48",
      "pesoMax": "23",
      "pesoMin": "16",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Cheerful, Alert, Intelligent, Attentive, Active",
      "image": "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
      "type": "api"
    },
    {
      "id": 104,
      "name": "English Toy Spaniel",
      "alturaMin": "25",
      "pesoMax": "6",
      "pesoMin": "4",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Reserved, Playful, Gentle, Happy, Loving",
      "image": "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
      "type": "api"
    },
    {
      "id": 105,
      "name": "English Toy Terrier",
      "alturaMax": "30",
      "alturaMin": "25",
      "pesoMax": "4",
      "pesoMin": "3",
      "vidaMax": "13 years",
      "vidaMin": "12",
      "temperaments": "Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable",
      "image": "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
      "type": "api"
    },
    {
      "id": 107,
      "name": "Eurasier",
      "alturaMax": "60",
      "alturaMin": "52",
      "pesoMax": "32",
      "pesoMin": "18",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm",
      "image": "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
      "type": "api"
    },
    {
      "id": 108,
      "name": "Field Spaniel",
      "alturaMax": "46",
      "alturaMin": "43",
      "pesoMax": "23",
      "pesoMin": "16",
      "vidaMax": "15 years",
      "vidaMin": "11",
      "temperaments": "Docile, Cautious, Sociable, Sensitive, Adaptable, Familial",
      "image": "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
      "type": "api"
    },
    {
      "id": 110,
      "name": "Finnish Lapphund",
      "alturaMax": "53",
      "alturaMin": "41",
      "pesoMax": "24",
      "pesoMin": "15",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Keen, Faithful, Calm, Courageous",
      "image": "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
      "type": "api"
    },
    {
      "id": 111,
      "name": "Finnish Spitz",
      "alturaMax": "51",
      "alturaMin": "39",
      "pesoMax": "13",
      "pesoMin": "10",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Playful, Loyal, Independent, Intelligent, Happy, Vocal",
      "image": "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
      "type": "api"
    },
    {
      "id": 113,
      "name": "French Bulldog",
      "alturaMax": "30",
      "alturaMin": "28",
      "pesoMin": "13",
      "vidaMax": "11 years",
      "vidaMin": "9",
      "temperaments": "Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright",
      "image": "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
      "type": "api"
    },
    {
      "id": 114,
      "name": "German Pinscher",
      "alturaMax": "51",
      "alturaMin": "43",
      "pesoMax": "20",
      "pesoMin": "11",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Spirited, Lively, Intelligent, Loving, Even Tempered, Familial",
      "image": "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
      "type": "api"
    },
    {
      "id": 115,
      "name": "German Shepherd Dog",
      "alturaMax": "66",
      "alturaMin": "56",
      "pesoMax": "41",
      "pesoMin": "23",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous",
      "image": "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
      "type": "api"
    },
    {
      "id": 116,
      "name": "German Shorthaired Pointer",
      "alturaMax": "64",
      "alturaMin": "53",
      "pesoMax": "32",
      "pesoMin": "20",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable",
      "image": "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
      "type": "api"
    },
    {
      "id": 119,
      "name": "Giant Schnauzer",
      "alturaMax": "70",
      "alturaMin": "60",
      "pesoMax": "41",
      "pesoMin": "29",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful",
      "image": "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
      "type": "api"
    },
    {
      "id": 120,
      "name": "Glen of Imaal Terrier",
      "alturaMax": "36",
      "alturaMin": "32",
      "pesoMax": "18",
      "pesoMin": "15",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Spirited, Agile, Loyal, Gentle, Active, Courageous",
      "image": "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
      "type": "api"
    },
    {
      "id": 121,
      "name": "Golden Retriever",
      "alturaMax": "61",
      "alturaMin": "55",
      "pesoMax": "34",
      "pesoMin": "25",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident",
      "image": "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
      "type": "api"
    },
    {
      "id": 123,
      "name": "Gordon Setter",
      "alturaMax": "69",
      "alturaMin": "58",
      "pesoMax": "36",
      "pesoMin": "20",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Fearless, Alert, Loyal, Confident, Gay, Eager",
      "image": "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
      "type": "api"
    },
    {
      "id": 124,
      "name": "Great Dane",
      "alturaMax": "81",
      "alturaMin": "71",
      "pesoMax": "86",
      "pesoMin": "50",
      "vidaMax": "10 years",
      "vidaMin": "7",
      "temperaments": "Friendly, Devoted, Reserved, Gentle, Confident, Loving",
      "image": "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
      "type": "api"
    },
    {
      "id": 125,
      "name": "Great Pyrenees",
      "alturaMax": "81",
      "alturaMin": "64",
      "pesoMax": "52",
      "pesoMin": "39",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident",
      "image": "https://cdn2.thedogapi.com/images/B12uzg9V7.png",
      "type": "api"
    },
    {
      "id": 127,
      "name": "Greyhound",
      "alturaMax": "76",
      "alturaMin": "69",
      "pesoMax": "32",
      "pesoMin": "23",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered",
      "image": "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
      "type": "api"
    },
    {
      "id": 128,
      "name": "Griffon Bruxellois",
      "alturaMax": "28",
      "alturaMin": "23",
      "pesoMin": "5",
      "vidaMin": "10 – 15 years",
      "temperaments": "Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful",
      "image": "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
      "type": "api"
    },
    {
      "id": 129,
      "name": "Harrier",
      "alturaMax": "56",
      "alturaMin": "46",
      "pesoMax": "27",
      "pesoMin": "18",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active",
      "image": "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
      "type": "api"
    },
    {
      "id": 130,
      "name": "Havanese",
      "alturaMax": "29",
      "alturaMin": "22",
      "pesoMax": "6",
      "pesoMin": "3",
      "vidaMax": "15 years",
      "vidaMin": "14",
      "temperaments": "Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
      "type": "api"
    },
    {
      "id": 134,
      "name": "Irish Setter",
      "alturaMax": "69",
      "alturaMin": "61",
      "pesoMax": "32",
      "pesoMin": "16",
      "vidaMax": "11 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Energetic, Lively, Independent, Playful, Companionable",
      "image": "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
      "type": "api"
    },
    {
      "id": 135,
      "name": "Irish Terrier",
      "alturaMin": "46",
      "pesoMax": "12",
      "pesoMin": "11",
      "vidaMax": "16 years",
      "vidaMin": "12",
      "temperaments": "Respectful, Lively, Intelligent, Dominant, Protective, Trainable",
      "image": "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
      "type": "api"
    },
    {
      "id": 137,
      "name": "Irish Wolfhound",
      "alturaMax": "89",
      "alturaMin": "76",
      "pesoMax": "82",
      "pesoMin": "48",
      "vidaMax": "8 years",
      "vidaMin": "6",
      "temperaments": "Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous",
      "image": "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
      "type": "api"
    },
    {
      "id": 138,
      "name": "Italian Greyhound",
      "alturaMax": "38",
      "alturaMin": "33",
      "pesoMax": "7",
      "pesoMin": "3",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
      "type": "api"
    },
    {
      "id": 140,
      "name": "Japanese Chin",
      "alturaMax": "28",
      "alturaMin": "20",
      "pesoMax": "4",
      "pesoMin": "2",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Alert, Loyal, Independent, Intelligent, Loving, Cat-like",
      "image": "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
      "type": "api"
    },
    {
      "id": 141,
      "name": "Japanese Spitz",
      "alturaMax": "38",
      "alturaMin": "30",
      "pesoMax": "9",
      "pesoMin": "7",
      "vidaMin": "10 – 16 years",
      "temperaments": "Affectionate, Obedient, Playful, Companionable, Intelligent, Proud",
      "image": "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
      "type": "api"
    },
    {
      "id": 142,
      "name": "Keeshond",
      "alturaMax": "46",
      "alturaMin": "43",
      "pesoMax": "20",
      "pesoMin": "16",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Agile, Obedient, Playful, Quick, Sturdy, Bright",
      "image": "https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg",
      "type": "api"
    },
    {
      "id": 144,
      "name": "Komondor",
      "alturaMax": "70",
      "alturaMin": "65",
      "pesoMax": "45",
      "pesoMin": "36",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Steady, Fearless, Affectionate, Independent, Gentle, Calm",
      "image": "https://cdn2.thedogapi.com/images/Bko0fl547.jpg",
      "type": "api"
    },
    {
      "id": 145,
      "name": "Kooikerhondje",
      "alturaMax": "41",
      "alturaMin": "36",
      "pesoMax": "14",
      "pesoMin": "9",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Benevolent, Agile, Alert, Intelligent, Active, Territorial",
      "image": "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
      "type": "api"
    },
    {
      "id": 147,
      "name": "Kuvasz",
      "alturaMax": "76",
      "alturaMin": "66",
      "pesoMax": "52",
      "pesoMin": "32",
      "vidaMax": "10 years",
      "vidaMin": "8",
      "temperaments": "Clownish, Loyal, Patient, Independent, Intelligent, Protective",
      "image": "https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg",
      "type": "api"
    },
    {
      "id": 149,
      "name": "Labrador Retriever",
      "alturaMax": "62",
      "alturaMin": "55",
      "pesoMax": "36",
      "pesoMin": "25",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered",
      "image": "https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg",
      "type": "api"
    },
    {
      "id": 151,
      "name": "Lagotto Romagnolo",
      "alturaMax": "48",
      "alturaMin": "41",
      "pesoMax": "16",
      "pesoMin": "11",
      "vidaMax": "16 years",
      "vidaMin": "14",
      "temperaments": "Keen, Loyal, Companionable, Loving, Active, Trainable",
      "image": "https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg",
      "type": "api"
    },
    {
      "id": 153,
      "name": "Lancashire Heeler",
      "alturaMax": "30",
      "alturaMin": "25",
      "pesoMax": "6",
      "pesoMin": "3",
      "vidaMin": "12 – 15 years",
      "temperaments": "Clever, Friendly, Alert, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/S1RGml5Em.jpg",
      "type": "api"
    },
    {
      "id": 155,
      "name": "Leonberger",
      "alturaMax": "80",
      "alturaMin": "65",
      "pesoMax": "77",
      "pesoMin": "54",
      "vidaMax": "8 years",
      "vidaMin": "6",
      "temperaments": "Obedient, Fearless, Loyal, Companionable, Adaptable, Loving",
      "image": "https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg",
      "type": "api"
    },
    {
      "id": 156,
      "name": "Lhasa Apso",
      "alturaMax": "28",
      "alturaMin": "25",
      "pesoMax": "8",
      "pesoMin": "5",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg",
      "type": "api"
    },
    {
      "id": 161,
      "name": "Maltese",
      "alturaMax": "25",
      "alturaMin": "20",
      "pesoMax": "3",
      "pesoMin": "2",
      "vidaMax": "18 years",
      "vidaMin": "15",
      "temperaments": "Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg",
      "type": "api"
    },
    {
      "id": 165,
      "name": "Miniature American Shepherd",
      "alturaMax": "46",
      "alturaMin": "33",
      "pesoMax": "18",
      "pesoMin": "9",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Energetic, Loyal, Intelligent, Trainable",
      "image": "https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg",
      "type": "api"
    },
    {
      "id": 167,
      "name": "Miniature Pinscher",
      "alturaMax": "32",
      "alturaMin": "25",
      "pesoMax": "5",
      "pesoMin": "4",
      "vidaMin": "15 years",
      "temperaments": "Clever, Outgoing, Friendly, Energetic, Responsive, Playful",
      "image": "https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg",
      "type": "api"
    },
    {
      "id": 168,
      "name": "Miniature Schnauzer",
      "alturaMax": "36",
      "alturaMin": "30",
      "pesoMax": "9",
      "pesoMin": "5",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Fearless, Friendly, Spirited, Alert, Obedient, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg",
      "type": "api"
    },
    {
      "id": 171,
      "name": "Newfoundland",
      "alturaMax": "71",
      "alturaMin": "66",
      "pesoMax": "68",
      "pesoMin": "45",
      "vidaMax": "10 years",
      "vidaMin": "8",
      "temperaments": "Sweet-Tempered, Gentle, Trainable",
      "image": "https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg",
      "type": "api"
    },
    {
      "id": 172,
      "name": "Norfolk Terrier",
      "alturaMax": "25",
      "alturaMin": "23",
      "pesoMax": "5",
      "pesoMin": "5",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable",
      "image": "https://cdn2.thedogapi.com/images/B1ADQg94X.jpg",
      "type": "api"
    },
    {
      "id": 176,
      "name": "Norwich Terrier",
      "alturaMin": "25",
      "pesoMax": "5",
      "pesoMin": "5",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Hardy, Affectionate, Energetic, Sensitive, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg",
      "type": "api"
    },
    {
      "id": 177,
      "name": "Nova Scotia Duck Tolling Retriever",
      "alturaMax": "53",
      "alturaMin": "43",
      "pesoMax": "23",
      "pesoMin": "16",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Outgoing, Alert, Patient, Intelligent, Loving",
      "image": "https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg",
      "type": "api"
    },
    {
      "id": 178,
      "name": "Old English Sheepdog",
      "alturaMin": "53",
      "pesoMax": "45",
      "pesoMin": "27",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving",
      "image": "https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg",
      "type": "api"
    },
    {
      "id": 179,
      "name": "Olde English Bulldogge",
      "alturaMax": "48",
      "alturaMin": "38",
      "pesoMin": "NaN",
      "vidaMin": "9 – 14 years",
      "temperaments": "Friendly, Alert, Confident, Loving, Courageous, Strong",
      "image": "https://cdn2.thedogapi.com/images/B1d5me547.jpg",
      "type": "api"
    },
    {
      "id": 181,
      "name": "Papillon",
      "alturaMax": "28",
      "alturaMin": "20",
      "pesoMax": "5",
      "pesoMin": "1",
      "vidaMax": "17 years",
      "vidaMin": "13",
      "temperaments": "Hardy, Friendly, Energetic, Alert, Intelligent, Happy",
      "image": "https://cdn2.thedogapi.com/images/SkJj7e547.jpg",
      "type": "api"
    },
    {
      "id": 183,
      "name": "Pekingese",
      "alturaMax": "23",
      "alturaMin": "15",
      "pesoMin": "6",
      "vidaMax": "18 years",
      "vidaMin": "14",
      "temperaments": "Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg",
      "type": "api"
    },
    {
      "id": 184,
      "name": "Pembroke Welsh Corgi",
      "alturaMax": "30",
      "alturaMin": "25",
      "pesoMax": "14",
      "pesoMin": "11",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Tenacious, Outgoing, Friendly, Bold, Playful, Protective",
      "image": "https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg",
      "type": "api"
    },
    {
      "id": 185,
      "name": "Perro de Presa Canario",
      "alturaMax": "65",
      "alturaMin": "56",
      "pesoMax": "50",
      "pesoMin": "40",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Strong Willed, Suspicious, Gentle, Dominant, Calm",
      "image": "https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg",
      "type": "api"
    },
    {
      "id": 188,
      "name": "Pharaoh Hound",
      "alturaMax": "64",
      "alturaMin": "53",
      "pesoMax": "27",
      "pesoMin": "18",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Sociable, Playful, Intelligent, Active, Trainable",
      "image": "https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg",
      "type": "api"
    },
    {
      "id": 189,
      "name": "Plott",
      "alturaMax": "64",
      "alturaMin": "51",
      "pesoMax": "27",
      "pesoMin": "18",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Bold, Alert, Loyal, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg",
      "type": "api"
    },
    {
      "id": 193,
      "name": "Pomeranian",
      "alturaMax": "30",
      "alturaMin": "20",
      "pesoMax": "3",
      "pesoMin": "1",
      "vidaMin": "15 years",
      "temperaments": "Extroverted, Friendly, Sociable, Playful, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/HJd0XecNX.jpg",
      "type": "api"
    },
    {
      "id": 196,
      "name": "Poodle (Miniature)",
      "alturaMax": "38",
      "alturaMin": "28",
      "pesoMax": "8",
      "pesoMin": "7",
      "vidaMin": "12 – 15 years",
      "image": "https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg",
      "type": "api"
    },
    {
      "id": 197,
      "name": "Poodle (Toy)",
      "alturaMax": "28",
      "alturaMin": "23",
      "pesoMax": "4",
      "pesoMin": "3",
      "vidaMin": "18 years",
      "image": "https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg",
      "type": "api"
    },
    {
      "id": 201,
      "name": "Pug",
      "alturaMax": "30",
      "alturaMin": "25",
      "pesoMax": "8",
      "pesoMin": "6",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive",
      "image": "https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg",
      "type": "api"
    },
    {
      "id": 204,
      "name": "Puli",
      "alturaMax": "43",
      "alturaMin": "41",
      "pesoMax": "16",
      "pesoMin": "11",
      "vidaMax": "16 Years years",
      "vidaMin": "12",
      "temperaments": "Energetic, Agile, Loyal, Obedient, Intelligent, Faithful",
      "image": "https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg",
      "type": "api"
    },
    {
      "id": 205,
      "name": "Pumi",
      "alturaMax": "47",
      "alturaMin": "38",
      "pesoMax": "15",
      "pesoMin": "8",
      "vidaMax": "15 years",
      "vidaMin": "13",
      "temperaments": "Lively, Reserved, Intelligent, Active, Protective, Vocal",
      "image": "https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg",
      "type": "api"
    },
    {
      "id": 207,
      "name": "Rat Terrier",
      "alturaMax": "33",
      "alturaMin": "25",
      "pesoMax": "11",
      "pesoMin": "4",
      "vidaMax": "18 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving",
      "image": "https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg",
      "type": "api"
    },
    {
      "id": 208,
      "name": "Redbone Coonhound",
      "alturaMax": "69",
      "alturaMin": "53",
      "pesoMax": "36",
      "pesoMin": "20",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Energetic, Independent, Companionable, Familial, Unflappable",
      "image": "https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg",
      "type": "api"
    },
    {
      "id": 209,
      "name": "Rhodesian Ridgeback",
      "alturaMax": "69",
      "alturaMin": "61",
      "pesoMax": "36",
      "pesoMin": "34",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/By9zNgqE7.jpg",
      "type": "api"
    },
    {
      "id": 210,
      "name": "Rottweiler",
      "alturaMax": "69",
      "alturaMin": "56",
      "pesoMax": "50",
      "pesoMin": "34",
      "vidaMax": "10 years",
      "vidaMin": "8",
      "temperaments": "Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous",
      "image": "https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg",
      "type": "api"
    },
    {
      "id": 211,
      "name": "Russian Toy",
      "alturaMax": "27",
      "alturaMin": "19",
      "pesoMax": "3",
      "pesoMin": "1",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "image": "https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg",
      "type": "api"
    },
    {
      "id": 212,
      "name": "Saint Bernard",
      "alturaMax": "70",
      "alturaMin": "65",
      "pesoMax": "82",
      "pesoMin": "59",
      "vidaMax": "10 years",
      "vidaMin": "7",
      "temperaments": "Friendly, Lively, Gentle, Watchful, Calm",
      "image": "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
      "type": "api"
    },
    {
      "id": 213,
      "name": "Saluki",
      "alturaMax": "71",
      "alturaMin": "58",
      "pesoMax": "29",
      "pesoMin": "16",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Aloof, Reserved, Intelligent, Quiet",
      "image": "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
      "type": "api"
    },
    {
      "id": 214,
      "name": "Samoyed",
      "alturaMax": "60",
      "alturaMin": "48",
      "pesoMax": "27",
      "pesoMin": "23",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Stubborn, Friendly, Sociable, Lively, Alert, Playful",
      "image": "https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg",
      "type": "api"
    },
    {
      "id": 216,
      "name": "Schipperke",
      "alturaMax": "33",
      "alturaMin": "25",
      "pesoMax": "7",
      "pesoMin": "5",
      "vidaMax": "15 years",
      "vidaMin": "13",
      "temperaments": "Fearless, Agile, Curious, Independent, Confident, Faithful",
      "image": "https://cdn2.thedogapi.com/images/SyBvVgc47.jpg",
      "type": "api"
    },
    {
      "id": 218,
      "name": "Scottish Deerhound",
      "alturaMax": "81",
      "alturaMin": "71",
      "pesoMax": "59",
      "pesoMin": "32",
      "vidaMax": "10 years",
      "vidaMin": "8",
      "temperaments": "Docile, Friendly, Dignified, Gentle",
      "image": "https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg",
      "type": "api"
    },
    {
      "id": 219,
      "name": "Scottish Terrier",
      "alturaMin": "25",
      "pesoMax": "10",
      "pesoMin": "8",
      "vidaMax": "13 years",
      "vidaMin": "11",
      "temperaments": "Feisty, Alert, Independent, Playful, Quick, Self-assured",
      "image": "https://cdn2.thedogapi.com/images/Bklnce5NX.jpg",
      "type": "api"
    },
    {
      "id": 221,
      "name": "Shetland Sheepdog",
      "alturaMax": "41",
      "alturaMin": "33",
      "pesoMin": "14",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong",
      "image": "https://cdn2.thedogapi.com/images/rJa29l9E7.jpg",
      "type": "api"
    },
    {
      "id": 222,
      "name": "Shiba Inu",
      "alturaMax": "42",
      "alturaMin": "34",
      "pesoMax": "10",
      "pesoMin": "8",
      "vidaMax": "16 years",
      "vidaMin": "12",
      "temperaments": "Charming, Fearless, Keen, Alert, Confident, Faithful",
      "image": "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
      "type": "api"
    },
    {
      "id": 223,
      "name": "Shih Tzu",
      "alturaMax": "28",
      "alturaMin": "20",
      "pesoMax": "7",
      "pesoMin": "4",
      "vidaMax": "18 years",
      "vidaMin": "10",
      "temperaments": "Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous",
      "image": "https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg",
      "type": "api"
    },
    {
      "id": 225,
      "name": "Shiloh Shepherd",
      "alturaMax": "76",
      "alturaMin": "66",
      "pesoMax": "64",
      "pesoMin": "54",
      "vidaMin": "9 – 14 years",
      "temperaments": "Outgoing, Loyal, Companionable, Gentle, Loving, Trainable",
      "image": "https://cdn2.thedogapi.com/images/SJJxjecEX.jpg",
      "type": "api"
    },
    {
      "id": 226,
      "name": "Siberian Husky",
      "alturaMax": "60",
      "alturaMin": "51",
      "pesoMax": "27",
      "pesoMin": "16",
      "vidaMin": "12 years",
      "temperaments": "Outgoing, Friendly, Alert, Gentle, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/S17ZilqNm.jpg",
      "type": "api"
    },
    {
      "id": 228,
      "name": "Silky Terrier",
      "alturaMax": "25",
      "alturaMin": "23",
      "pesoMax": "5",
      "pesoMin": "4",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Responsive, Inquisitive, Alert, Quick, Joyful",
      "image": "https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg",
      "type": "api"
    },
    {
      "id": 232,
      "name": "Smooth Fox Terrier",
      "alturaMin": "39",
      "pesoMax": "8",
      "pesoMin": "NaN",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Fearless, Affectionate, Alert, Playful, Intelligent, Active",
      "image": "https://cdn2.thedogapi.com/images/Syszjx9Em.jpg",
      "type": "api"
    },
    {
      "id": 233,
      "name": "Soft Coated Wheaten Terrier",
      "alturaMax": "46",
      "alturaMin": "41",
      "pesoMax": "18",
      "pesoMin": "14",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful",
      "image": "https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg",
      "type": "api"
    },
    {
      "id": 235,
      "name": "Spanish Water Dog",
      "alturaMax": "51",
      "alturaMin": "41",
      "pesoMax": "23",
      "pesoMin": "14",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg",
      "type": "api"
    },
    {
      "id": 236,
      "name": "Spinone Italiano",
      "alturaMax": "70",
      "alturaMin": "57",
      "pesoMax": "39",
      "pesoMin": "28",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Docile, Friendly, Affectionate, Loyal, Patient, Gentle",
      "image": "https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg",
      "type": "api"
    },
    {
      "id": 238,
      "name": "Staffordshire Bull Terrier",
      "alturaMax": "41",
      "alturaMin": "36",
      "pesoMax": "17",
      "pesoMin": "11",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous",
      "image": "https://cdn2.thedogapi.com/images/H1zSie9V7.jpg",
      "type": "api"
    },
    {
      "id": 239,
      "name": "Standard Schnauzer",
      "alturaMax": "50",
      "alturaMin": "44",
      "pesoMax": "23",
      "pesoMin": "14",
      "vidaMax": "15 years",
      "vidaMin": "13",
      "temperaments": "Trainable, Good-natured, Devoted, Lively, Playful, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
      "type": "api"
    },
    {
      "id": 242,
      "name": "Swedish Vallhund",
      "alturaMax": "34",
      "alturaMin": "29",
      "pesoMax": "14",
      "pesoMin": "9",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Fearless, Friendly, Energetic, Alert, Intelligent, Watchful",
      "image": "https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg",
      "type": "api"
    },
    {
      "id": 243,
      "name": "Thai Ridgeback",
      "alturaMax": "61",
      "alturaMin": "51",
      "pesoMax": "25",
      "pesoMin": "16",
      "vidaMax": "12 years",
      "vidaMin": "10",
      "temperaments": "Protective, Loyal, Independent, Intelligent, Loving, Familial",
      "image": "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
      "type": "api"
    },
    {
      "id": 244,
      "name": "Tibetan Mastiff",
      "alturaMax": "66",
      "alturaMin": "61",
      "pesoMax": "64",
      "pesoMin": "39",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective",
      "image": "https://cdn2.thedogapi.com/images/SkM9sec47.jpg",
      "type": "api"
    },
    {
      "id": 245,
      "name": "Tibetan Spaniel",
      "alturaMin": "25",
      "pesoMax": "7",
      "pesoMin": "4",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy",
      "image": "https://cdn2.thedogapi.com/images/Hyjcol947.jpg",
      "type": "api"
    },
    {
      "id": 246,
      "name": "Tibetan Terrier",
      "alturaMax": "43",
      "alturaMin": "36",
      "pesoMax": "11",
      "pesoMin": "9",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive",
      "image": "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
      "type": "api"
    },
    {
      "id": 248,
      "name": "Toy Fox Terrier",
      "alturaMax": "28",
      "alturaMin": "20",
      "pesoMax": "4",
      "pesoMin": "2",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Spirited, Alert, Loyal, Playful, Intelligent",
      "image": "https://cdn2.thedogapi.com/images/B17ase9V7.jpg",
      "type": "api"
    },
    {
      "id": 250,
      "name": "Treeing Walker Coonhound",
      "alturaMax": "69",
      "alturaMin": "51",
      "pesoMax": "36",
      "pesoMin": "20",
      "vidaMax": "13 years",
      "vidaMin": "10",
      "temperaments": "Clever, Affectionate, Confident, Intelligent, Loving, Trainable",
      "image": "https://cdn2.thedogapi.com/images/SkRpsgc47.jpg",
      "type": "api"
    },
    {
      "id": 251,
      "name": "Vizsla",
      "alturaMax": "61",
      "alturaMin": "53",
      "pesoMax": "29",
      "pesoMin": "23",
      "vidaMax": "14 years",
      "vidaMin": "10",
      "temperaments": "Affectionate, Energetic, Loyal, Gentle, Quiet",
      "image": "https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg",
      "type": "api"
    },
    {
      "id": 253,
      "name": "Weimaraner",
      "alturaMax": "69",
      "alturaMin": "58",
      "pesoMax": "41",
      "pesoMin": "25",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast",
      "image": "https://cdn2.thedogapi.com/images/SyU12l9V7.jpg",
      "type": "api"
    },
    {
      "id": 254,
      "name": "Welsh Springer Spaniel",
      "alturaMax": "48",
      "alturaMin": "43",
      "pesoMax": "25",
      "pesoMin": "16",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Stubborn, Friendly, Affectionate, Loyal, Playful, Active",
      "image": "https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg",
      "type": "api"
    },
    {
      "id": 256,
      "name": "West Highland White Terrier",
      "alturaMax": "28",
      "alturaMin": "25",
      "pesoMax": "10",
      "pesoMin": "7",
      "vidaMax": "20 years",
      "vidaMin": "15",
      "temperaments": "Hardy, Friendly, Alert, Independent, Gay, Active, Courageous",
      "image": "https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg",
      "type": "api"
    },
    {
      "id": 257,
      "name": "Whippet",
      "alturaMax": "56",
      "alturaMin": "46",
      "pesoMax": "16",
      "pesoMin": "11",
      "vidaMax": "15 years",
      "vidaMin": "12",
      "temperaments": "Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet",
      "image": "https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg",
      "type": "api"
    },
    {
      "id": 258,
      "name": "White Shepherd",
      "alturaMax": "64",
      "alturaMin": "56",
      "pesoMax": "39",
      "pesoMin": "27",
      "vidaMin": "12 – 14 years",
      "temperaments": "Self-confidence, Aloof, Fearless, Alert, Companionable, Eager",
      "image": "https://cdn2.thedogapi.com/images/r14M3e9E7.jpg",
      "type": "api"
    },
    {
      "id": 259,
      "name": "Wire Fox Terrier",
      "alturaMax": "41",
      "alturaMin": "33",
      "pesoMax": "9",
      "pesoMin": "7",
      "vidaMin": "13 – 14 years",
      "temperaments": "Fearless, Friendly, Bold, Keen, Alert, Quick",
      "image": "https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg",
      "type": "api"
    },
    {
      "id": 260,
      "name": "Wirehaired Pointing Griffon",
      "alturaMax": "61",
      "alturaMin": "51",
      "pesoMax": "32",
      "pesoMin": "20",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Loyal, Gentle, Vigilant, Trainable, Proud",
      "image": "https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg",
      "type": "api"
    },
    {
      "id": 261,
      "name": "Wirehaired Vizsla",
      "alturaMax": "64",
      "alturaMin": "55",
      "pesoMax": "29",
      "pesoMin": "20",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "image": "https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg",
      "type": "api"
    },
    {
      "id": 262,
      "name": "Xoloitzcuintli",
      "alturaMax": "58",
      "alturaMin": "25",
      "pesoMax": "14",
      "pesoMin": "4",
      "vidaMax": "14 years",
      "vidaMin": "12",
      "temperaments": "Cheerful, Alert, Companionable, Intelligent, Protective, Calm",
      "image": "https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg",
      "type": "api"
    },
    {
      "id": 264,
      "name": "Yorkshire Terrier",
      "alturaMax": "23",
      "alturaMin": "20",
      "pesoMax": "3",
      "pesoMin": "2",
      "vidaMax": "16 years",
      "vidaMin": "12",
      "temperaments": "Bold, Independent, Confident, Intelligent, Courageous",
      "image": "https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg",
      "type": "api"
    }
  ]